### ISSUE TITLE
Posts that start with Arabic words should has rtl direction

### ISSUE THREAD

**Issue by medhatdawoud** [egyptian-geeks/website#7]

**Comment by emad-elsaid** [comment]
I think @Microsmsm is already working on this issue

**Comment by emad-elsaid** [comment]
https://github.com/egyptian-geeks/website/commit/ff1a4a514d67d24fb27c8ffb38a6c1e44deabf1d fixed this

**Comment by medhatdawoud** [comment]
@emad-elsaid  Is that deployed already to server ? because I cannot see the change

**Comment by emad-elsaid** [comment]
humm maybe you mean something different with that issue, so the fix is the text direction not the alignment, the following is the change:

this is the new direction, if it had arabic the direction is rtl.
![screen shot 2018-02-08 at 11 29 42](https://user-images.githubusercontent.com/54403/35968209-7fbad6b2-0cc3-11e8-9eee-c650316f6c23.png)

this is the old behaviour, it's ltr.
![screen shot 2018-02-08 at 11 31 45](https://user-images.githubusercontent.com/54403/35968282-b00682e4-0cc3-11e8-95be-28436093a761.png)

so this is what you meant with this issue right, or you meant the alignment?

**Comment by medhatdawoud** [comment]
No I mean both of them, the text alignment and the direction should be fixed

**Comment by emad-elsaid** [comment]
ahaaa, in that case I solved one part, can you  take a look on how to align text automatically depending on the language direction? as I think there is no "auto" value for the text alignment

**Comment by emad-elsaid** [comment]
solved with dir=auto
